const TIPS = [
  'Press Esc to interrupt Claude mid-turn and steer it somewhere else.',
  'Start a prompt with ! to run a shell command right in the session.',
  'Type @ to mention a file and pull it straight into your prompt.',
  'Shift+Tab cycles permission modes, plan mode included.',
  '/compact squeezes a long conversation down so it stays sharp.',
  '/clear starts fresh when you switch to a new task.',
  'claude --continue picks up your most recent conversation.',
  '/model switches models without leaving the session.',
  '/helix-dex shows every spinner verb you have collected.',
  '/helix-demo shows every spinner animation side by side.',
  'Any verb can turn up golden. Shinies are about 1 in 1,000.',
  'There are 20 secret rare verbs. Have you found them all?',
  'Press Esc twice (or use /rewind) to jump back to an earlier message and optionally restore the code.',
  'claude -r lets you pick a past conversation to resume.',
  '/resume switches to a past conversation without leaving the session.',
  '/context shows what is taking up the context window.',
  '/memory opens your CLAUDE.md memory files for editing.',
  '/init writes a starter CLAUDE.md for your project.',
  'A CLAUDE.md in a subfolder gets loaded when Claude works in that folder.',
  'Ctrl+O toggles the full transcript view.',
  'Ctrl+R searches your prompt history.',
  'The up arrow brings back your previous prompts.',
  '/btw asks a quick side question without derailing the main task.',
  '/effort changes how hard the model thinks.',
  '/cost shows the tokens and cost of this session.',
  '/permissions lets you review and edit what Claude may do without asking.',
  '/hooks shows the hooks you have configured.',
  '/config opens settings like theme and model.',
  '/export saves the conversation so you can share it.',
  'Paste an image into the prompt and Claude can read it: screenshots, mockups, error dialogs.',
  'claude -p "your prompt" runs Claude once and prints the answer. Great for scripts.',
  'claude --add-dir gives Claude access to another folder, like a sibling repo.',
  'Give Claude a way to check its work, like tests or a build command, and results get much better.',
  'For big changes, ask for a plan first and review it before any code is written.',
  'Paste the exact error message instead of describing it.',
  'Point Claude at an existing file to copy the style from.',
  'Start a fresh conversation for unrelated tasks. Long contexts get noisy.',
  'Say what "done" looks like: the behavior, the files and the tests.',
  'Ask "what could go wrong with this?" to surface edge cases early.',
  'If Claude heads the wrong way, interrupt early and redirect rather than waiting.',
]

const FACTS = [
  'Octopuses have three hearts and blue blood.',
  'Honey never spoils: edible honey has turned up in ancient Egyptian tombs.',
  'Bananas are berries. Strawberries are not.',
  'A group of flamingos is called a flamboyance.',
  'Wombats make cube-shaped poop.',
  'Sea otters hold hands while they sleep so they do not drift apart.',
  "Scotland's national animal is the unicorn.",
  'The Eiffel Tower grows about 15 cm taller in summer as the iron expands.',
  'A day on Venus is longer than a year on Venus.',
  "A shrimp's heart is in its head.",
  'Butterflies taste with their feet.',
  'The dot over a lowercase i or j is called a tittle.',
  'Pluto has not finished a single orbit since it was discovered in 1930.',
  'The shortest war on record, Britain versus Zanzibar in 1896, lasted under an hour.',
  'Earth has more trees than the Milky Way has stars.',
  'Sloths can hold their breath for up to 40 minutes.',
  'Woolly mammoths were still alive when the Great Pyramid of Giza was built.',
  'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.',
  'Oxford University is older than the Aztec Empire.',
  'Sharks have been around longer than trees.',
  'Squirrels are a leading cause of power outages in the United States.',
  'Elephants are one of the few mammals that cannot jump.',
  "An octopus's main heart stops beating while it swims, so it prefers to crawl.",
  'Male seahorses are the ones that get pregnant and give birth.',
  'Axolotls can regrow lost limbs and even repair parts of their heart, brain and spine.',
  'Wood frogs can freeze solid in winter and thaw back to life in spring.',
  'Flamingo parents feed their chicks a bright red "crop milk".',
  'Some turtles can breathe through their butts.',
  'Bananas are slightly radioactive, thanks to their potassium.',
  'A bolt of lightning is about five times hotter than the surface of the Sun.',
  'A fluffy cumulus cloud can weigh around a million pounds.',
  'Hawaiian pizza was invented in Canada.',
  'The inventor of the Pringles can had some of his ashes buried in one.',
  'There is a basketball court above the US Supreme Court, nicknamed "the highest court in the land".',
  'In 1932 Australia sent soldiers with machine guns to fight emus. The emus won.',
  'In 1919 a tank of molasses burst in Boston and a wave of syrup swept through the streets at about 35 mph.',
  'In 1858 the River Thames smelled so bad that it nearly shut down the British Parliament: the Great Stink.',
  'In the 1830s ketchup was sold in the US as medicine, in pill form.',
  'In 1952 Albert Einstein was offered the presidency of Israel. He turned it down.',
  'Abraham Lincoln is in the National Wrestling Hall of Fame.',
  'Tardigrades survived being flown on the outside of a spacecraft, exposed to the vacuum of space.',
  'Crows can recognize human faces and hold a grudge against people who wronged them for years.',
  'A pistol shrimp snaps its claw so fast it makes a bubble nearly as hot as the surface of the Sun.',
  'The Moon drifts about 3.8 cm farther from Earth every year.',
  'Your stomach grows a fresh lining every few days so it does not digest itself.',
  'A pineapple takes about two years to grow.',
  'Koala fingerprints are so similar to ours they could confuse a crime scene.',
  'Cats cannot taste sweetness.',
  'Rats make ultrasonic laughing sounds when they are tickled.',
  'Polar bears have black skin under their white-looking fur.',
  'One man had the hiccups for 68 years straight.',
  'Nintendo, Jack the Ripper and the Ottoman Empire all existed at the same time.',
  'There are more stars in the observable universe than grains of sand on all of Earth\'s beaches.',
  'A teaspoon of neutron star would weigh more than every human on Earth combined.',
  'Saturn is less dense than water. In a big enough bathtub, it would float.',
  'Sunlight takes about 8 minutes to reach Earth, so you always see the Sun as it was 8 minutes ago.',
  'Your body replaces roughly 330 billion cells every day.',
  'Your stomach acid could dissolve metal. A layer of mucus keeps it from dissolving you.',
  'Nerve signals can travel at around 270 mph.',
  'Your heart beats about 100,000 times a day.',
  'Cows have best friends and get stressed when they are separated.',
  'Dolphins give themselves signature whistles that work like names.',
  'Sea otters have a pocket of loose skin under each arm where they keep a favorite rock.',
  'Honeybees tell each other where food is by dancing.',
  'Ravens can plan ahead, saving a tool now for a task they expect later.',
  'Octopuses can taste things with their suckers.',
  'Goats have rectangular pupils.',
  'Starfish do not have a brain.',
  'Jellyfish have been around for over 500 million years, longer than dinosaurs.',
  'Hummingbirds are the only birds that can fly backwards.',
  'Owls cannot move their eyes, so they turn their whole head instead.',
]

const HISTORY = [
  'In 1947 engineers found an actual moth in the Harvard Mark II and taped it into the log book as the first bug.',
  'JavaScript was first written in about ten days, in 1995.',
  'The first .com domain, symbolics.com, was registered on March 15, 1985.',
  'The first webcam watched a coffee pot at the University of Cambridge in 1991, so nobody walked to an empty pot.',
  'The first spam email went out in 1978: an ad from DEC to a few hundred ARPANET users.',
  'The first text message, sent in 1992, said "Merry Christmas" and was typed on a computer, not a phone.',
  'The first YouTube video, "Me at the zoo", is 19 seconds of a co-founder talking about elephants.',
  'The Apollo Guidance Computer ran at about 2 MHz, slower than a modern pocket calculator.',
  'Nintendo was founded in 1889 to make hanafuda playing cards.',
  "Douglas Engelbart's first computer mouse, built in the 1960s, had a carved wooden shell and one button.",
  'Ray Tomlinson picked the @ symbol for email addresses in 1971.',
  'Ctrl+Alt+Delete was created by IBM engineer David Bradley.',
  "Apple's first logo, from 1976, was a drawing of Isaac Newton sitting under a tree.",
  'Bluetooth is named after Harald Bluetooth, a 10th-century Danish king.',
  'Google is named after a googol, the number 1 followed by 100 zeros.',
  'Python is named after Monty Python, not the snake.',
  'Email is older than the World Wide Web by about two decades.',
  'Brain, one of the first PC viruses, was written in 1986 by two brothers in Pakistan.',
  'The first website, info.cern.ch, went live in 1991, and you can still visit it today.',
  'The Konami Code (up up down down left right left right B A) was a cheat a developer made because his game was too hard to test.',
  'The term "Easter egg" comes from Atari\'s Adventure (1980), where Warren Robinett hid his name because Atari would not credit him.',
  'Junk email is called spam because of a 1970 Monty Python sketch where Vikings sing "Spam" over everything.',
  'Ada Lovelace published what is often called the first computer program in 1843.',
  'The QWERTY keyboard layout was designed for typewriters in the 1870s.',
  'Space Invaders speeds up as you play because there are fewer aliens to draw, a quirk the designer kept.',
  'Pac-Man was originally called Puck-Man in Japan.',
  'The first iPhone launched in 2007 without an App Store. That came a year later.',
  'Wi-Fi does not stand for anything. It was a brand name dreamed up by a marketing firm.',
  'Firefox was first released under the name Phoenix.',
  'Amazon was almost named Cadabra.',
  'CAPTCHA stands for Completely Automated Public Turing test to tell Computers and Humans Apart.',
  'The first hard drive, IBM\'s 350 from 1956, held about 5 million characters and was the size of two refrigerators.',
  'Linus Torvalds says Linux has a penguin mascot because a penguin once bit him at a zoo.',
  'Tetris was made in 1984 by Alexey Pajitnov in Moscow. Its name mixes "tetra" with tennis, his favorite sport.',
  'Because of Soviet rules, Pajitnov earned nothing from Tetris for years.',
  "Minecraft's Creeper came from a bug: Notch mixed up the height and length of the pig model.",
  'Microsoft Solitaire was partly there to teach people how to drag and drop with a mouse. An intern wrote it.',
  'Steve Jobs was employee #40 at Atari, and he brought in Steve Wozniak to help build Breakout.',
  'Scott Fahlman proposed the first smiley emoticon, :-), in 1982.',
  '"Hello, World!" as a first program goes back to Brian Kernighan\'s tutorials in the 1970s.',
  'One of the first video games, Spacewar!, was written at MIT in 1962.',
  'The creator of the GIF said it is pronounced "jif".',
  'Java was originally called Oak.',
  'Linus Torvalds wrote the first version of Git in a matter of days in 2005.',
  'The word "robot" comes from R.U.R., a Czech play from 1920.',
  'The first handheld mobile phone call, in 1973, was made by a Motorola engineer to a rival at Bell Labs.',
  'YouTube was first pitched as a video dating site.',
  '"Computer" used to be a job title for people who did calculations by hand.',
  'ENIAC, an early computer from 1945, weighed about 30 tons.',
  "Bill Gates' first program played tic-tac-toe.",
  'Thomas Edison was calling technical glitches "bugs" back in 1878.',
  'Ethernet is named after the "luminiferous ether" that physicists once thought filled space.',
]

const REMINDERS = [
  'Make sure to drink some water.',
  'Roll your shoulders back and unclench your jaw.',
  'Look at something far away for 20 seconds. Your eyes will thank you.',
  'Stand up and stretch while this runs.',
  'Take a deep breath in... and out.',
  'Have you eaten something today?',
  'Check your posture. Sit up tall!',
  'Blink a few times. Screens make us forget.',
  'Grab a snack if you are hungry.',
  'A short walk can untangle a tricky problem.',
  'You are doing great. Seriously.',
  'Text someone you have not talked to in a while.',
  'Step outside for some fresh air soon.',
  'Refill your water bottle while you wait.',
  'It is okay to take a break.',
  'Wiggle your toes. Just because.',
  'Drop your shoulders away from your ears.',
  'When did you last stand up? Now is a great time.',
  'Give your wrists a gentle stretch.',
  'Put on a song you love.',
  'Water break! Your future self says thanks.',
]

// Interleaved so a run of lines mixes tips, facts, tech history and reminders.
export type TipLine = { kind: 'Tip' | 'Fun fact' | 'Tech history' | 'Reminder'; text: string }

export const TIP_LINES: readonly TipLine[] = Array.from(
  { length: Math.max(TIPS.length, FACTS.length, HISTORY.length, REMINDERS.length) },
  (_, index) => [
    TIPS[index] && { kind: 'Tip' as const, text: TIPS[index] },
    FACTS[index] && { kind: 'Fun fact' as const, text: FACTS[index] },
    HISTORY[index] && { kind: 'Tech history' as const, text: HISTORY[index] },
    REMINDERS[index] && { kind: 'Reminder' as const, text: REMINDERS[index] },
  ],
)
  .flat()
  .filter((line): line is TipLine => Boolean(line))
